apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2021-02-11T13:34:43Z'
  generation: 3
  labels:
    app: sidecar
  name: sidecar
  namespace: test-sidecar
  resourceVersion: '179675'
  selfLink: /apis/apps.openshift.io/v1/namespaces/test-sidecar/deploymentconfigs/sidecar
  uid: e610654f-6c6d-11eb-9129-08002754380e
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: sidecar
    deploymentconfig: sidecar
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: sidecar
        deploymentconfig: sidecar
    spec:
      containers:
        - image: >-
            172.30.1.1:5000/test-sidecar/minishift-test@sha256:063e287b881209449e943eea25240104a58b0a8a28e7a06e16006ef2816c02b1
          imagePullPolicy: Always
          name: sidecar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - image: >-
            172.30.1.1:5000/test-sidecar/nginx@sha256:b66a7138157b12ff98f6fd86d8102f74159b26772c685a6d8f56ce0d988b1290
          imagePullPolicy: Always
          name: sidecar-1
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - sidecar
        from:
          kind: ImageStreamTag
          name: 'minishift-test:latest'
          namespace: test-sidecar
        lastTriggeredImage: >-
          172.30.1.1:5000/test-sidecar/minishift-test@sha256:063e287b881209449e943eea25240104a58b0a8a28e7a06e16006ef2816c02b1
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - sidecar-1
        from:
          kind: ImageStreamTag
          name: 'nginx:latest'
          namespace: test-sidecar
        lastTriggeredImage: >-
          172.30.1.1:5000/test-sidecar/nginx@sha256:b66a7138157b12ff98f6fd86d8102f74159b26772c685a6d8f56ce0d988b1290
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2021-02-11T13:47:34Z'
      lastUpdateTime: '2021-02-11T13:47:37Z'
      message: replication controller "sidecar-2" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2021-02-11T17:08:20Z'
      lastUpdateTime: '2021-02-11T17:08:20Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
  details:
    causes:
      - imageTrigger:
          from:
            kind: DockerImage
            name: >-
              172.30.1.1:5000/test-sidecar/minishift-test@sha256:063e287b881209449e943eea25240104a58b0a8a28e7a06e16006ef2816c02b1
        type: ImageChange
    message: image change
  latestVersion: 2
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1