apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: minishift-test
    openshift.io/deployment-config.name: minishift-test
  name: minishift-test-1
  namespace: test
  ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: minishift-test
      uid: 1222f638-69f3-11eb-8e7e-08002754380e
  resourceVersion: '97626'
  selfLink: /api/v1/namespaces/test/replicationcontrollers/minishift-test-1
  uid: 127875c7-69f3-11eb-abbf-08002754380e
spec:
  replicas: 1
  selector:
    app: minishift-test
    deployment: minishift-test-1
    deploymentconfig: minishift-test
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: '1'
        openshift.io/deployment-config.name: minishift-test
        openshift.io/deployment.name: minishift-test-1
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: minishift-test
        deployment: minishift-test-1
        deploymentconfig: minishift-test
    spec:
      containers:
        - image: >-
            172.30.1.1:5000/test/minishift_test@sha256:4e1c4eacc56f36f509ca8963cd4b28e9e0d3d30ca7626f25bc4a0a6fc8e05b3f
          imagePullPolicy: Always
          name: minishift-test
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
