apiVersion: v1
kind: Service
metadata:
  labels:
    app: minishift-test
  name: minishift-test
  namespace: test
spec:
  clusterIP: 172.30.93.126
  ports:
    - name: 1080-1080
      port: 1080
      protocol: TCP
      targetPort: 1080
  selector:
    app: minishift-test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
